blueprint:
  name: Định vị ô tô thông minh
  description: Tự động phát hiện ô tô về nhà và mở cửa
  domain: automation
  input:
    switch_entity1:
      name: công tắc ảo
      description: cần tạo 1 công tắc ảo theo link https://github.com/javishome/blueprint/edit/main/virtual_switch1.yaml
      selector:
        entity:
          domain: switch
    switch_entity2:
      name: module định vị ô tô
      description: chọn module định vị ô tô đã mua từ JAVIS
      selector:
        entity:
          domain: switch
trigger:
  - platform: time_pattern
    seconds: /3
variables:
  switch_entity1: !input switch_entity1
  switch_entity2: !input switch_entity2
condition: []
action:
  - service_template: >
      {% if (is_state(switch_entity1, "on")) %}  
        mqtt.publish
      {% endif %}
    data:
      topic_template: "zigbee2mqtt/{{ switch_entity2.split('.')[1] }}/get"
      payload: "{\"state\": \"\"}"
