blueprint:
  name: Định vị ô tô thông minh
  description: Tự động phát hiện ô tô về nhà và mở cửa. Module định vị ô tô là module định vị ô tô đã mua từ JAVIS
  domain: automation
  input:
    sensor_entity1:
      name: sensor ảo
      selector:
        entity:
          domain: sensor
    switch_entity2:
      name: module định vị ô tô
      selector:
        entity:
          domain: switch
trigger:
  - platform: time_pattern
    seconds: /3
variables:
  sensor_entity1: !input sensor_entity1
  switch_entity2: !input switch_entity2
condition: []
action:
  - service_template: >
      {% if (is_state(sensor_entity1, "on")) %}  
        mqtt.publish
      {% endif %}
    data:
      topic_template: "zigbee2mqtt/{{ switch_entity2.split('.')[1] }}/get"
      payload: "{\"state\": \"\"}"