blueprint:
  name: autocar
  description: Auto detect car by JAVIS module
  domain: automation
  input:
    switch_entity1:
      name: Switch auto
      selector:
        entity:
          domain: switch
    switch_entity2:
      name: Switch real
      selector:
        entity:
          domain: switch
trigger:
  - platform: time_pattern
    seconds: /3
variables:
  switch_entity1: !input switch_entity1
  switch_entity2: !input switch_entity2
condition: []
action:
  - service_template: >
      {% if (is_state(switch_entity1, "on")) %}  
        mqtt.publish
      {% endif %}
    data:
      topic_template: "zigbee2mqtt/{{ switch_entity2.split('.')[1] }}/get"
      payload: "{\"state\": \"\"}"
