blueprint:
  name: đồng bộ 2 chiều công tắc
  description: Đồng bộ trạng thái công tắc 2 chiều
  domain: automation
  input:
    switch_1:
      name: Switch 1
      selector:
        entity:
          domain: switch
    switch_2:
      name: Switch 2
      selector:
        entity:
          domain: switch
variables:
  switch_1: !input switch_1
  switch_2: !input switch_2
trigger:
  - platform: state
    entity_id: 
      - !input switch_1
      - !input switch_2
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: 
      - !input switch_1
      - !input switch_2
    from: 'off'
    to: 'on'
# condition: "{{ trigger.to_state.context.parent_id == none }}"
action:
  - service_template: >
      {% if trigger.entity_id == switch_1 %}
        {% if is_state(switch_1, "off") and is_state(switch_2, "on") %}  
        switch.turn_off
        {% elif (is_state(switch_1, "on")) and (is_state(switch_2, "off")) %}
        switch.turn_on
        {% endif %}
      {% elif trigger.entity_id == switch_2 %}
        {% if is_state(switch_2, "off") and is_state(switch_1, "on") %}  
        switch.turn_off
        {% elif (is_state(switch_2, "on")) and (is_state(switch_1, "off")) %}
        switch.turn_on   
        {% endif %}
      {% endif %} 
    data_template: 
      entity_id: >
        {% if trigger.entity_id == switch_1 %}
        {{ switch_2 }}
        {% elif trigger.entity_id == switch_2 %}
        {{ switch_1 }}
        {% endif %}