blueprint:
  name: đồng bộ 2 chiều công tắc và đèn
  description: Đồng bộ trạng thái công tắc và đèn
  domain: automation
  input:
    switch_1:
      name: Switch 1
      selector:
        entity:
          domain: switch
          multiple: false
    light_2:
      name: Light 2
      selector:
        entity:
          domain: light
          multiple: false
  source_url: https://raw.githubusercontent.com/javishome/blueprint/main/sync_switch_light.yaml
variables:
  switch_1: !input switch_1
  light_2: !input light_2
trigger:
- platform: state
  entity_id:
  - !input switch_1
  from: 'on'
  to: 'off'
  id: check_off_1
- platform: state
  entity_id:
  - !input light_2
  from: 'on'
  to: 'off'
  id: check_off_2
- platform: state
  entity_id:
  - !input switch_1
  from: 'off'
  to: 'on'
  id: check_on_1
- platform: state
  entity_id:
  - !input light_2
  from: 'off'
  to: 'on'
  id: check_on_2
action:
  - choose:
    - conditions: 
        - condition: trigger
          id: check_on_1
        - condition: state
          entity_id: !input light_2
          state: 'off'
      sequence:
      - service: light.turn_on
        target:
          entity_id: !input light_2
  - choose:
    - conditions: 
        - condition: trigger
          id: check_on_2
        - condition: state
          entity_id: !input switch_1
          state: 'off'
      sequence:
      - service: switch.turn_on
        target:
          entity_id: !input switch_1
  - choose:
    - conditions: 
        - condition: trigger
          id: check_off_1
        - condition: state
          entity_id: !input light_2
          state: 'on'
      sequence:
      - service: light.turn_off
        target:
          entity_id: !input light_2
  - choose:
    - conditions: 
        - condition: trigger
          id: check_off_2
        - condition: state
          entity_id: !input switch_1
          state: 'on'
      sequence:
      - service: switch.turn_off
        target:
          entity_id: !input switch_1
    default:
      - choose: []
        default: []
mode: single 
max_exceeded: silent
