blueprint:
  name: Đồng bộ 2 công tắc
  description: Đồng bộ (đảo chiều) trạng thái 2 công tắc
  domain: automation
  input:
    switch_1:
      name: Switch 1
      selector:
        entity:
          domain: switch
    switch_2:
      name: Switch 2
      selector:
        entity:
          domain: switch
  source_url: https://github.com/javishome/blueprint/blob/main/sync_1switch.yaml
variables:
  switches:
  - !input 'switch_1'
  - !input 'switch_2'
trigger:
- platform: state
  entity_id:
  - !input 'switch_1'
  - !input 'switch_2'
mode: queued
max_exceeded: silent
condition:
- condition: template
  value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'
- condition: template
  value_template: "{{ trigger.to_state.context.parent_id is none or  (trigger.to_state.context.id\
    \         != this.context.id and \n trigger.to_state.context.parent_id  != this.context.id)\
    \ }}\n"
action:
- service: switch.turn_{{ trigger.to_state.state }}
  target:
    entity_id:  >
        {% if trigger.entity_id == switch_1 %}
        {{ switch_2 }}
        {% endif %}
