blueprint:
  name: đồng bộ 1 chiều công tắc
  description: Đồng bộ trạng thái công tắc 1 chiều, công tắc sau đổi trạng thái theo công tắc trước
  domain: automation
  input:
    switch_1:
      name: Switch 1
      selector:
        entity:
          domain: switch
          multiple: false
    switch_2:
      name: Switch 2
      selector:
        entity:
          domain: switch
          multiple: false
  source_url: https://raw.githubusercontent.com/javishome/blueprint/main/sync_switch_1way.yaml
variables:
  switch_1: !input switch_1
  switch_2: !input switch_2
trigger:
- platform: state
  entity_id:
  - !input switch_1
  from: 'on'
  to: 'off'
  id: check_off_1
- platform: state
  entity_id:
  - !input switch_1
  from: 'off'
  to: 'on'
  id: check_on_1
action:
  - choose:
    - conditions: 
        - condition: trigger
          id: check_on_1
        - condition: state
          entity_id: !input switch_2
          state: 'off'
      sequence:
      - service: switch.turn_on
        target:
          entity_id: !input switch_2
  - choose:
    - conditions: 
        - condition: trigger
          id: check_off_1
        - condition: state
          entity_id: !input switch_2
          state: 'on'
      sequence:
      - service: switch.turn_off
        target:
          entity_id: !input switch_2
    default:
      - choose: []
        default: []
mode: single 
max_exceeded: silent
