blueprint:
  name: đồng bộ 1 chiều công tắc
  description: Đồng bộ trạng thái công tắc 1 chiều
  domain: automation
  input:
    switch_entity1:
      name: Switch 1
      selector:
        entity:
          domain: switch
    switch_entity2:
      name: Switch 2
      selector:
        entity:
          domain: switch
variables:
  switch_entity1: !input switch_entity1
  switch_entity2: !input switch_entity2
trigger:
  - platform: state
    entity_id: 
      - !input switch_entity1
      - !input switch_entity2
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: 
      - !input switch_entity1
      - !input switch_entity2
    from: 'off'
    to: 'on'
# condition: "{{ trigger.to_state.context.parent_id == none }}"
action:
  - service_template: >
      {% if trigger.entity_id == switch_entity1 %}
        {% if is_state(switch_entity1, "off") and is_state(switch_entity2, "on") %}  
        switch.turn_off
        {% elif (is_state(switch_entity1, "on")) and (is_state(switch_entity2, "off")) %}
        switch.turn_on
        {% endif %}
      {% endif %} 
    data_template: 
      entity_id: >
        {% if trigger.entity_id == switch_entity1 %}
        {{ switch_entity2 }}
        {% endif %}